export const currencyConstants = {
    GET_CURRENCY_LIST_REQUEST: 'GET_CURRENCY_LIST_REQUEST',
    GET_CURRENCY_LIST_SUCCESS: 'GET_CURRENCY_LIST_SUCCESS',
    GET_CURRENCY_LIST_FAILURE: 'GET_CURRENCY_LIST_FAILURE',
}
