export const currencyConstants = {
    GET_CURRENCY_LIST_REQUEST: 'GET_CURRENCY_LIST_REQUEST',
    GET_CURRENCY_LIST_SUCCESS: 'GET_CURRENCY_LIST_SUCCESS',
    GET_CURRENCY_LIST_FAILURE: 'GET_CURRENCY_LIST_FAILURE',

    // convert currency
    CONVERT_CURRENCY_REQUEST: 'CONVERT_CURRENCY_REQUEST',
    CONVERT_CURRENCY_SUCCESS: 'CONVERT_CURRENCY_SUCCESS',
    CONVERT_CURRENCY_FAILURE: 'CONVERT_CURRENCY_FAILURE',
}
